# Site settings
title: State of the Map LATAM 2017
email: info@osmlatam.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
destination: docs
url: "http://state.osmlatam.org" # the base hostname & protocol for your site
baseurl:
twitter_username:
github_username:
exclude: [README.md]

# Build settings
markdown: kramdown

# Translations
t:
  en:
    language_name: English
    menu:
      about:
        label: About
        url: /en/#about
      venue:
        label: Venue
        url: /en/#venue
  es:
    language_name: Español
    menu:
      about:
        label: Sobre
        url: /#about
      venue:
        label: Local
        url: /#venue
  pt:
    language_name: Português
    menu:
      about:
        label: Sobre
        url: /pt/#about
      venue:
        label: Local
        url: /pt/#venue
